services:

  app:
    build: 
    environment:
      DB_URL: jdbc:postgresql://backend-postgres-1:5432/appdb
      DB_USER: app
      DB_PASSWORD: app

      JWT_SECRET: please-change-me
      JWT_ISSUER: ktor.io
      JWT_AUDIENCE: ktor-audience

      PORT: "8080"
    ports:
      - "8080:8080"

volumes:
  pgdata:
